#
# Table structure for table 'tx_camaliga_domain_model_content'
#
CREATE TABLE tx_camaliga_domain_model_content (

	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,

	title varchar(255) DEFAULT '' NOT NULL,
	shortdesc text NOT NULL,
	longdesc text NOT NULL,
	link tinytext NOT NULL,
	image tinytext NOT NULL,
	image2 tinytext NOT NULL,
	caption2 varchar(255) DEFAULT '' NOT NULL,
	image3 tinytext NOT NULL,
	caption3 varchar(255) DEFAULT '' NOT NULL,
	image4 tinytext NOT NULL,
	caption4 varchar(255) DEFAULT '' NOT NULL,
	image5 tinytext NOT NULL,
	caption5 varchar(255) DEFAULT '' NOT NULL,
	falimage int(11) unsigned NOT NULL default '0',
	falimage2 int(11) unsigned NOT NULL default '0',
	falimage3 int(11) unsigned NOT NULL default '0',
	falimage4 int(11) unsigned NOT NULL default '0',
	falimage5 int(11) unsigned NOT NULL default '0',
	street varchar(255) DEFAULT '' NOT NULL,
	zip varchar(255) DEFAULT '' NOT NULL,
	city varchar(255) DEFAULT '' NOT NULL,
	country varchar(255) DEFAULT '' NOT NULL,
	person varchar(255) DEFAULT '' NOT NULL,
	phone varchar(255) DEFAULT '' NOT NULL,
	mobile varchar(255) DEFAULT '' NOT NULL,
	email varchar(255) DEFAULT '' NOT NULL,
	latitude decimal(24,14) DEFAULT '0.00000000000000',
	longitude decimal(24,14) DEFAULT '0.00000000000000',
	custom1 varchar(255) DEFAULT '' NOT NULL,
	custom2 varchar(255) DEFAULT '' NOT NULL,
	custom3 varchar(255) DEFAULT '' NOT NULL,
	mother int(11) unsigned DEFAULT '0' NOT NULL,

	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,

	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	t3_origuid int(11) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,

	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
	KEY language (l10n_parent,sys_language_uid)

);
