services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quizpalme\Camaliga\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Quizpalme\Camaliga\Backend\EventListener\PreviewEventListener:
    tags:
      - name: "event.listener"
        identifier: 'camaliga/preview-rendering'